#!/usr/bin/env bash

# Read input once (from file args or stdin)
input=$(cat "$@")

# Build OSC 52 escape sequence for clipboard
seq=$(echo -n "$input" | base64 | tr -d "\r\n")
seq="\ePtmux;\e\e]52;c;$seq\a\e\\"

if grep -q "microsoft" /proc/version && command -v clip.exe >/dev/null 2>&1; then
  echo -n "$input" | clip.exe
elif [[ ! -z "${SSH_TTY}" ]]; then
  [[ ! -z "${TMUX}" ]] && export $(tmux showenv SSH_TTY)
  printf "$seq" > "$SSH_TTY"
elif [[ ! -z "${TMUX}" ]]; then
  pane_active_tty=$(tmux list-panes -F "#{pane_active} #{pane_tty}" | awk '$1=="1" { print $2 }')
  printf "$seq" > "$pane_active_tty"
# macOS
elif command -v pbcopy >/dev/null 2>&1; then
  echo -n "$input" | pbcopy
# Linux xclip
elif command -v xclip >/dev/null 2>&1; then
  echo -n "$input" | xclip -selection clipboard
# Linux xsel
elif command -v xsel >/dev/null 2>&1; then
  echo -n "$input" | xsel --clipboard --input
else
  printf "$seq" > /dev/fd/2
fi
