#|      _    _                 _ _   _           |#
#|     / \  | | __ _  ___ _ __(_) |_| |_ _   _   |#
#|    / _ \ | |/ _` |/ __| '__| | __| __| | | |  |#
#|   / ___ \| | (_| | (__| |  | | |_| |_| |_| |  |#
#|  /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |  |#
#|                                       |___/   |#

# Window
# {{{
window:
  dynamic_padding: true
  padding:
    x: 3
    y: 3
  decorations: full
# }}}

# Fonts
# {{{
font:
  size: 16
# }}}

# Theme
# {{{
# One Half Dark
colors:
  primary:
    background: '#282c34'
    foreground: '#dcdfe4'

  normal:
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#e5c07b'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#dcdfe4'

  bright:
    black:  '#5c6370'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#e5c07b'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#dcdfe4'
# }}}

# Mappings
# {{{
key_bindings:
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: W, mods: Control|Shift, action: Quit }
  - { key: T, mods: Control|Shift, chars: "\eT" }
  - { key: Tab, mods: Control, chars: "\e)" }
  - { key: Tab, mods: Control|Shift, chars: "\e(" }

  # Windows
  - { key: Left, mods: Alt, chars: "\e[1~" } # Home
  - { key: Right, mods: Alt, chars: "\e[4~" } # End

  # Mac
  - { key: B, mods: Command, chars: "\eb" } # one word left
  - { key: F, mods: Command, chars: "\ef" } # one word right
  - { key: H, mods: Command, chars: "\eh" } # M-h
  - { key: J, mods: Command, chars: "\ej" } # M-j
  - { key: K, mods: Command, chars: "\ek" } # M-k
  - { key: L, mods: Command, chars: "\el" } # M-l
# }}}
