# herdr-pwa: phone/laptop front-end for herdr (github.com/WilliamHsieh/herdr-pwa).
# The app's code lives in its own git clone and tracks upstream; this module only
# declares how to run it: a user service, a one-shot env bootstrap, and the
# `herdr-pwa-update` command that clones/pulls + builds + restarts. Nothing here
# touches the network during activation, and no secret enters the repo.
#
# Per-machine knobs live under programs.herdr-pwa.* (repoUrl/repoDir/port), so a
# second deployment (e.g. a work machine behind a different VPN, HTTPS clone URL)
# only overrides options in home/default.nix keyed on dotfiles.hostname.
#
# One-time manual steps (not declarative):
#   sudo tailscale up            # tailnet + enable HTTPS certs in the admin console
#   herdr-pwa-update             # first clone + build; unit starts once dist/ exists
#   tailscale serve --bg http://127.0.0.1:<port>
#   iPhone Safari -> open the serve URL -> Add to Home Screen -> paste token from
#   ~/.config/herdr-pwa/env
# Without Tailscale (e.g. corporate network): keep HOST=127.0.0.1 and reach it
# through an SSH local port-forward from the phone; localhost counts as a secure
# context, so the PWA still installs.
{
  pkgs,
  lib,
  config,
  dotfiles,
  ...
}:
let
  cfg = config.programs.herdr-pwa;
  envDir = "${config.xdg.configHome}/herdr-pwa";
  envFile = "${envDir}/env";

  # Mirrors upstream .env.example. VAPID keys are generated by the app on first
  # start when left blank. Voice transcription (faster-whisper + CUDA wheels +
  # large-v3 model) is off by default: WHISPER_RUNNER=/bin/false makes the
  # warmup fail loudly in the log and nothing else; delete that line to enable.
  envTemplate = pkgs.writeText "herdr-pwa-env.template" ''
    PORT=${toString cfg.port}
    HOST=127.0.0.1
    HERDR_SOCKET_PATH=${config.xdg.configHome}/herdr/herdr.sock
    HERDR_AUTH_TOKEN=@TOKEN@
    HERDR_MODE=live
    UPLOAD_DIR=./data/uploads
    MAX_IMAGE_UPLOAD_MB=15
    MAX_FILE_UPLOAD_MB=100
    MAX_VIDEO_UPLOAD_MB=250
    MAX_AUDIO_UPLOAD_MB=25
    PUSH_DATA_DIR=./data/push
    VAPID_SUBJECT=mailto:${dotfiles.email}
    VAPID_PUBLIC_KEY=
    VAPID_PRIVATE_KEY=
    WHISPER_RUNNER=/bin/false
    WHISPER_MODEL=large-v3
    WHISPER_DEVICE=auto
    CLAUDE_CREDENTIALS_PATH=${config.home.homeDirectory}/.claude/.credentials.json
    AI_USAGE_CACHE_DIR=${config.xdg.cacheHome}/herdr-pwa
    CODEX_BIN=codex
  '';

  update = pkgs.writeShellScriptBin "herdr-pwa-update" ''
    set -euo pipefail
    export PATH="${
      lib.makeBinPath [
        pkgs.git
        pkgs.nodejs
        pkgs.openssh
      ]
    }:$PATH"
    if [ ! -d "${cfg.repoDir}/.git" ]; then
      echo "herdr-pwa-update: cloning ${cfg.repoUrl} -> ${cfg.repoDir}"
      git clone "${cfg.repoUrl}" "${cfg.repoDir}"
    else
      git -C "${cfg.repoDir}" pull --ff-only
    fi
    cd "${cfg.repoDir}"
    npm ci
    npm run build
    ${lib.optionalString pkgs.stdenv.isLinux ''
      systemctl --user restart herdr-pwa.service
      systemctl --user --no-pager status herdr-pwa.service | head -5
    ''}
  '';
in
{
  options.programs.herdr-pwa = {
    enable = lib.mkEnableOption "herdr-pwa gateway: user service, env bootstrap and herdr-pwa-update";

    repoUrl = lib.mkOption {
      type = lib.types.str;
      default = "git@github.com:WilliamHsieh/herdr-pwa.git";
      description = "Git URL herdr-pwa-update clones from (use https:// where the machine has no GitHub SSH key).";
    };

    repoDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/weithers/oss/herdr-pwa";
      description = "Where the herdr-pwa checkout lives; the service runs `npm start` here.";
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 8787;
      description = "Loopback port the gateway listens on; expose it via `tailscale serve` or an SSH tunnel.";
    };
  };

  config = lib.mkIf cfg.enable {
    warnings =
      lib.optional (!pkgs.stdenv.isLinux)
        "programs.herdr-pwa: the user service is systemd-only; on this platform only herdr-pwa-update and the env file are managed.";

    home.packages = [ update ];

    # Write the env file once with a fresh bearer token; never overwrite so the
    # token the phone already has stays valid. Delete the file to rotate.
    home.activation.initHerdrPwaEnv = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ ! -f "${envFile}" ]; then
        run mkdir -p "${envDir}"
        token="$(${pkgs.openssl}/bin/openssl rand -hex 32)"
        run ${pkgs.gnused}/bin/sed "s#@TOKEN@#$token#" "${envTemplate}" > "${envFile}"
        run chmod 600 "${envFile}"
        echo "initHerdrPwaEnv: wrote ${envFile} (new token; see file to pair the phone)"
      fi
    '';

    systemd.user.services.herdr-pwa = lib.mkIf pkgs.stdenv.isLinux {
      Unit = {
        Description = "Herdr Remote PWA gateway";
        After = [ "network-online.target" ];
        Wants = [ "network-online.target" ];
        # Only meaningful after the first `herdr-pwa-update` has built dist/.
        ConditionPathExists = "${cfg.repoDir}/dist";
      };
      Service = {
        Type = "simple";
        WorkingDirectory = cfg.repoDir;
        EnvironmentFile = envFile;
        Environment = [
          # node-pty spawns the real herdr client; point at the installer's binary
          # instead of relying on the (minimal) systemd user PATH.
          "HERDR_BIN=${config.home.homeDirectory}/.local/bin/herdr"
          "PATH=${lib.makeBinPath [ pkgs.nodejs ]}:${config.home.homeDirectory}/.local/bin:/usr/bin"
        ];
        ExecStart = "${pkgs.nodejs}/bin/npm start";
        Restart = "on-failure";
        RestartSec = 3;
        NoNewPrivileges = true;
        PrivateTmp = true;
        # Upstream's example adds ProtectHome=read-only; that blocks connect() on
        # the herdr Unix socket under ~/.config, so it is deliberately omitted.
      };
      Install.WantedBy = [ "default.target" ];
    };
  };
}
